export const constants = {
  IMAGE_FOLDER: {
    COMIC: "comic",
    USER: "user",
    AUTHOR: "author",
    CHAPTER: "chapter",
    COINPACKAGE: "coinPackage",
    DECORATE: "decorate",
  },
  COMIC_STATUS: {
    IN_PROCESS: "INPROCESS",
    DONE: "DONE",
    INACTIVE: "INACTIVE",
  },
  COMMON_STATUS: {
    ACTIVE: "ACTIVE",
    IN_ACTIVE: "INACTIVE",
    SUCCESS: "SUCCESS",
    FAILD: "FAILD",
  },
  TIME_LINE: {
    WEEK: "week",
    MONTH: "month",
  },
  GENDER: {
    NONE: "NONE",
    MALE: "MALE",
    FEMALE: "FEMALE",
  },
  TICKET_STATUS: {
    EXPIRED: "EXPIRED",
    ACTIVE: "ACTIVE",
    UNREGISTER: "UNREGISTER",
  },
  TRANSACTION_STATUS: {
    EXPIRED: "EXPIRED",
    SUCCESS: "SUCCESS",
    FAILED: "FAILED",
    CANCELED: "CANCELED",
    INPROCESS: "INPROCESS",
  },
  ATTENDANCE: {
    0: "Chủ Nhật",
    1: "Thứ 2",
    2: "Thứ 3",
    3: "Thứ 4",
    4: "Thứ 5",
    5: "Thứ 6",
    6: "Thứ 7",
  },
  USER_AVATAR: "user/avatar.png",
  AUTHOR_AVATAR: "author/avatar.png",
  DATE_TIME_FORMAT: "HH:mm  DD-MM-YYYY",
  DATE_FORMAT: "DD-MM-YYYY",
  NOTIFICATION_ACTION: {
    VIP_TICKET: "vipticket",
    // COIN_PACKAGE: 'coinPackage',
    NONE: "none",
    NEW_COMIC: "newcomic",
    NEW_CHAPTER: "newchapter",
  },
};
