export const OTP_TYPES = {
    LOGIN: 'LOGIN',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    REGISTER: 'REGISTER',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    CHANGE_PIN: 'CHANGE_PIN',
    CHANGE_PIN_SUCCESS: 'CHANGE_PIN_SUCCESS',
    FORGOT_PIN: 'FORGOT_PIN',
    FORGOT_PIN_SUCCESS: 'FORGOT_PIN_SUCCESS',
}

export const OTP_TIME_EXPIRE = 10 * 60 * 1000